version: "3"
services:
  reverseproxy:
      image: mdfa/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: mdfa/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: "udagrammddev"
      POSTGRESS_PASSWORD: "Amar0esh"
      POSTGRESS_DB: "udagrammddev" 
      POSTGRESS_HOST: "udagrammddev.cad0n8jn65i1.eu-central-1.rds.amazonaws.com" 
      AWS_REGION: "eu-central-1" 
      AWS_PROFILE: "default" 
      AWS_BUCKET: "udagram-mds-dev"
      JWT_SECRET: "shokalhobekobe"
      URL: "*"
  backend-feed:
    image: mdfa/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: "udagrammddev"
      POSTGRESS_PASSWORD: "Amar0esh" 
      POSTGRESS_DB: "udagrammddev" 
      POSTGRESS_HOST: "udagrammddev.cad0n8jn65i1.eu-central-1.rds.amazonaws.com" 
      AWS_REGION: "eu-central-1"
      AWS_PROFILE: "default" 
      AWS_BUCKET: "udagram-mds-dev"
      JWT_SECRET: "shokalhobekobe"
      URL: "*"
  frontend:
    image: mdfa/udacity-frontend:local
    ports:
      - "8100:80"
